### ISSUE TITLE
Getting started instructions should reference src/secret.js

### ISSUE THREAD

**Issue by glynnbird** [ibm-watson-data-lab/shopping-list-preact-pouchdb#39]
If I follow the startup instructions on this project, it doesn't work. I get the error:

> could not resolve ./src/secret

It turns out there's hard-coded Cloudant credentials required in a `./src/secret.js` file. There is a `./src/secret.js.template` file provided as a guide but this is not mentioned in the README at all.

**Comment by ptitzler** [comment]
The current implementation seems to be a place holder for the replication URL setting that users _should_ be able to configure in the app.

**Comment by ptitzler** [comment]
Related #43

**Comment by glynnbird** [comment]
no need to fix anymore
